### ISSUE TITLE
Expressive compatibility

### ISSUE THREAD

**Issue by michalbundyra** [northwoods/container#11]
Hello!

Just letting you know that we recently published container configuration documentation:
https://docs.zendframework.com/zend-expressive/v3/features/container/config/
We are working on library which covers all these cases and deliver common tests to check if the container is compatible and behave as expected, please see http://github.com/weierophinney/zend-container-config-test and the latest PR with tests updates:
https://github.com/weierophinney/zend-container-config-test/pull/4
We have already prepared fixed for Aura.Di and Pimple containers:
- zendframework/zend-auradi-config#10
- zendframework/zend-pimple-config#10

Would be nice if also this library is updated to use common tests. Please bare in mind it's still dev version, and the structure can be changes, but I think at this point we have quite good coverage of the desired behaviour.

**Comment by shadowhand** [comment]
I absolutely love the common test approach! Identified a ton of bugs with my implementation which are now resolved.
