### ISSUE TITLE
Delegators not working correctly

### ISSUE THREAD

**Issue by gdsmith** [northwoods/container#14]
Seems like `delegators` in zend-expressive should map to Auryn's `Injector::prepare`. The current implementation is only coupled to `factories` and `invokables` and doesn't allow you to use a delegator on it's own.

**Comment by gdsmith** [comment]
I see there are issues with the expected implementation of delegators that doesn't fit with how Auryn prepare works. Will it be possible to at least get delegators working for classes that don't have factories?

**Comment by shadowhand** [comment]
I am using [zend-container-config-test](https://github.com/zendframework/zend-container-config-test) and all tests are passing. If there is a missing feature from those tests, please report it there.
