### ISSUE TITLE
InjectorContainer has to implement Interop\Container\ContainerInterface too

### ISSUE THREAD

**Issue by ch-feedbackpeople** [northwoods/container#19]
Hello!

I'm using Zend Eventmanager and when initializing a LazyListenerAggregate (https://docs.zendframework.com/zend-eventmanager/lazy-listeners/lazy-listener-aggregate/) the aggregate needs the current container as a second argument.

Problem is, that this container still has to implement \Interop\Container\ContainerInterface and not \Psr\Container\ContainerInterface. As long as this is not fixed in the zend eventmanager package (and probably others) it would be good if the InjectorContainer simply implements the interop container too.

    use Psr\Container\ContainerInterface;
    use Interop\Container\ContainerInterface as InteropContainerInterface;

    class InjectorContainer implements ContainerInterface, InteropContainerInterface

This does not break anything and compatibility/usability with other packages is improved.

**Comment by shadowhand** [comment]
Patches welcome. 😁

**Comment by shadowhand** [comment]
Fixed by #19.
